//
//  SFIMacros.h
//  SecurifiApp
//
//  Created by K Murali Krishna on 13/12/16.
//  Copyright © 2016 Securifi Ltd. All rights reserved.
//

#define NAME_CHANGED_OWNED_ALMOND   1
#define NAME_CHANGED_SHARED_ALMOND  2

#define DELETE_ACCOUNT_CONFIRMATION     0
#define UNLINK_ALMOND_CONFIRMATION      1
#define USER_INVITE_ALERT               2

#define EXPANDED_PROFILE_ROW_HEIGHT 520
#define EXPANDED_OWNED_ALMOND_ROW_HEIGHT 170
#define EXPANDED_SHARED_ALMOND_ROW_HEIGHT 120

#define ACCOUNTS_ALERT_ONINVITETOSHAREALMOND_INVITE @"accounts.alert.onInviteToShareAlmond.Invite"
#define ACCOUNTS_ALERT_ONINVITETOSHAREALMOND_CANCEL @"accounts.alert.onInviteToShareAlmond.Cancel"
#define INVITE @"Invite"
#define INVITE_BY_EMAIL @"Invite By Email"
#define ACCOUNTS_ALERT_ONINVITETOSHAREDALMOND_TITLE @"accounts.alert.onInviteToShareAlmond.title"
#define ACCOUNTS_ALERT_ONINVITETOSHAREDALMOND_MESSAGE @"accounts.alert.onInviteToShareAlmond.message"
#define ACCOUNTS_ALERT_ONUNLINKALMOND_UNLINK @"accounts.alert.onUnlinkAlmond.Unlink"
#define ACCOUNTS_ALERT_ONUNLINKALMOND_CANCEL @"accounts.alert.onUnlinkAlmond.Cancel"
#define TO_CONFIRM_UNLNKING_ALMOND_ENTER_YOUR_PASSWORD_BELOW @"To confirm unlinking Almond enter your password below."
#define ACCOUNTS_ALERT_ONUNLINKALMOND_MESSAGE @"accounts.alert.onUnlinkAlmond.message"
#define UNLINK_ALMOND @"Unlink Almond"
#define ACCOUNTS_ALERT_ONUNLINKALMOND_TITLE @"accounts.alert.onUnlinkAlmond.title"
#define REMOVE_USER_FROM_SHARED_LIST @"Remove user from shared list..."
#define ACCOUNTS_HUD_REMOVEUSERFROMSHAREDLIST @"accounts.hud.removeUserFromSharedList"
#define REMOVE_SHARED_ALMOND @"Remove shared almond..."
#define ACCOUNTS_HUD_REMOVESHAREDALMOND @"accounts.hud.removeSharedAlmond"
#define DELETING_ACCOUNT @"Deleting account..."
#define ACCOUNTS_HUD_DELETINGACCOUNT @"accounts.hud.deletingAccount"
#define UNLINKING_ALMOND @"Unlinking Almond..."
#define ACCOUNTS_HUD_UNLINKINGALMOND @"accounts.hud.unlinkingAlmond"
#define INVITING_USER_TO_SHARE_ALMOND @"Inviting user to share Almond..."
#define ACCOUNT_HUD_INVITEUSERTOSHAREALMOND @"accounts.hud.inviteUserToShareAlmond"
#define SORRY_DELETION_OF_ACCOUNT_WAS_UNSUCCESSFUL @"Sorry! Deletion of account was unsuccessful."
#define ACCOUNTS_DELETEACCOUNT_FAILURE_DEFAULT @"accounts.deleteAccount.failure.default"
#define UPDATING_ACCOUNT_DETAILS @"Updating account details..."
#define ACCOUNTS_HUD_UPDATINGDETAILS @"accounts.hud.updatingDetails"
#define SORRY_UPDATE_WAS_UNSUCCESSFUL @"Sorry! Update was unsuccessful."
#define ACCOUNTS_UPDATEACCOUNT_FAILURE_DEFAULT @"accounts.updateAccount.failure.default"
#define SORRY_UNLINKING_OF_ALMOND_WAS_UNSUCCESSFUL @"Sorry! Unlinking of Almond was unsuccessful."
#define ACCOUNTS_UNLINKALMOND_FAILURE_DEFAULT @"accounts.unlinkAlmond.failure.default"
#define SORRY_SHARING_OF_ALMOND_WAS_UNSUCCESSFUL @"Sorry! Sharing of Almond was unsuccessful."
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_DEFAULT @"accounts.inviteUserToShareAlmond.failure.default"
#define ACCOUNTS_ITOAST_UNABLETOCHANGEALMONDNAME @"accounts.itoast.unableToChangeAlmondName"
#define SORRY_REMOVING_OF_SHARED_ALMOND_WAS_UNSUCCESSFUL @"Sorry! Removing of shared Almond was unsuccessful."
#define ACCOUNTS_DELETEMEASSECONDARYUSER_FAILURE_DEFAULT @"accounts.deleteMeAsSecondaryUser.failure.default"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE1 @"accounts.unlinkAlmond.failure.reasonCode1"
#define THERE_WAS_SOME_ERROR_ON_CLOUD_PLEASE_TRY_LATER @"There was some error on cloud. Please try later."
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE2 @"accounts.unlinkAlmond.failure.reasonCode2"
#define SORRY_YOU_ARE_NOT_REGISTERED_WITH_US_YET @"Sorry! You are not registered with us yet."
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE3 @"accounts.unlinkAlmond.failure.reasonCode3"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE4 @"accounts.unlinkAlmond.failure.reasonCode4"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE5 @"accounts.unlinkAlmond.failure.reasonCode5"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE6 @"accounts.unlinkAlmond.failure.reasonCode6"
#define YOU_NEED_TO_ACTIVATE_YOUR_ACCOUNT @"You need to activate your account."
#define YOU_NEED_TO_FILL_ALL_THE_FIELDS @"You need to fill all the fields."
#define THE_CURRENT_PASSWORD_WAS_INCORRECT @"The current password was incorrect."
#define ACCOUNTS_DELETEMEASSECONDARYUSER_FAILURE_REASONCODE1 @"accounts.deleteMeAsSecondaryUser.failure.reasonCode1"
#define ACCOUNTS_DELETEMEASSECONDARYUSER_FAILURE_REASONCODE2 @"accounts.deleteMeAsSecondaryUser.failure.reasonCode2"
#define ACCOUNTS_DELETEMEASSECONDARYUSER_FAILURE_REASONCODE3 @"accounts.deleteMeAsSecondaryUser.failure.reasonCode3"
#define YOU_ARE_NOT_ASSOCIATED_WITH_THIS_ALMOND @"You are not associated with this Almond."
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE1 @"accounts.inviteUserToShareAlmond.failure.reasonCode1"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE2 @"accounts.inviteUserToShareAlmond.failure.reasonCode2"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE3 @"accounts.inviteUserToShareAlmond.failure.reasonCode3"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE4 @"accounts.inviteUserToShareAlmond.failure.reasonCode4"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE5 @"accounts.inviteUserToShareAlmond.failure.reasonCode5"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE6 @"accounts.inviteUserToShareAlmond.failure.reasonCode6"
#define ACCOUNTS_INVITEUSERTOSHAREALMOND_FAILURE_REASONCODE7 @"accounts.inviteUserToShareAlmond.failure.reasonCode7"
#define THIS_USER_DOES_NOT_HAVE_A_SECURIFI_ACCOUNT @"This user does not have a Securifi account."
#define THE_USER_HAS_NOT_VERIFIED_THE_SECURIFI_ACCOUNT_YET @"The user has not verified the Securifi account yet."
#define YOU_DO_NOT_OWN_THIS_ALMOND @"You do not own this almond."
#define YOU_HAVE_ALREADY_SHARED_THIS_ALMOND_WITH_THE_USER @"You have already shared this almond with the user."
#define YOU_CAN_NOT_ADD_YOURSELF_AS_SECONDARY_USER @"You can not add yourself as secondary user."
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE1 @"accounts.unlinkAlmond.failure.reasonCode1"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE2 @"accounts.unlinkAlmond.failure.reasonCode2"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE3 @"accounts.unlinkAlmond.failure.reasonCode3"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE4 @"accounts.unlinkAlmond.failure.reasonCode4"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE5 @"accounts.unlinkAlmond.failure.reasonCode5"
#define ACCOUNTS_UNLINKALMOND_FAILURE_REASONCODE6 @"accounts.unlinkAlmond.failure.reasonCode6"
#define ACCOUNTS_UPDATEACCOUNT_FAILURE_REASONCODE1 @"accounts.updateAccount.failure.reasonCode1"
#define ACCOUNTS_UPDATEACCOUNT_FAILURE_REASONCODE2 @"accounts.updateAccount.failure.reasonCode2"
#define ACCOUNTS_UPDATEACCOUNT_FAILURE_REASONCODE3 @"accounts.updateAccount.failure.reasonCode3"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE1 @"accounts.deleteAccount.failure.reasonCode1"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE2 @"accounts.deleteAccount.failure.reasonCode2"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE3 @"accounts.deleteAccount.failure.reasonCode3"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE4 @"accounts.deleteAccount.failure.reasonCode4"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE5 @"accounts.deleteAccount.failure.reasonCode5"
#define ACCOUNTS_DELETEACCOUNT_FAILURE_REASONCODE6 @"accounts.deleteAccount.failure.reasonCode6"
#define ACCOUNTS_USERPROFILE_LABEL_FIRSTNAME @"accounts.userprofile.label.firstName"
#define ACCOUNTS_USERPROFILE_LABEL_LASTNAME @"accounts.userprofile.label.lastName"
#define ACCOUNTS_USERPROFILE_LABEL_ADDRESS @"accounts.userprofile.label.address"
#define ACCOUNTS_USERPROFILE_LABEL_COUNTRY @"accounts.userprofile.label.country"
#define ACCOUNTS_USERPROFILE_LABEL_ZIPCODE @"accounts.userprofile.label.zipCode"
#define FIRST_NAME @"FIRST NAME"
#define LAST_NAME @"LAST NAME"
#define ADDRESS @"ADDRESS"
#define COUNTRY @"COUNTRY"
#define ZIP_CODE @"ZIP CODE"
#define ACCOUNTS_NAVBAR_TITLE_SETTINGS @"accounts.navbar-title.settings"
#define ACCOUNTS_SETTINGS @"Accounts Settings"
#define ACCOUNTS_HUD_LOADINGDETAILS @"accounts.hud.loadingDetails"
#define LOADING_ACCOUNT_DETAILS @"Loading account details..."
#define ACCOUNTS_USERPROFILE_TITLE_ACCOUNT @"accounts.userprofile.title.account"
#define ACCOUNTS @"Accounts"
#define ACCOUNTS_USERPROFILE_TITLE_PLACEHOLDER_NAME @"accounts.userprofile.title.placeholder.name"
#define WE_DONT_KNOW_YOUR_NAME_YET @"We don't know your name yet"
#define ACCOUNTS_USERPROFILE_LABEL_PRIMARYEMAIL @"accounts.userprofile.label.primaryEmail"
#define PRIMARY_EMAIL @"PRIMARY EMAIL"
#define ACCOUNTS_USERPROFILE_LABEL_PASSWORD @"accounts.userprofile.label.password"
#define PASSWORD @"PASSWORD"
#define LINE @"line"
#define DOWN_ARROW @"down_arrow"
#define UP_ARROW @"up_arrow"
#define ACCOUNTS_OWNEDALMOND_LABEL_DEVICENAME @"accounts.ownedAlmond.label.deviceName"
#define ACCOUNTS_USERPROFILE_BUTTON_CHANGEPASSWORD @"accounts.userprofile.button.changePassword"
#define CHANGE_PASSWORD @"Change Password"
#define ACCOUNTS_USERPROFILE_BUTTON_ADD @"accounts.userprofile.button.add"
#define ADD @"add"
#define ACCOUNTS_USERPROFILE_BUTTON_EDIT @"accounts.userprofile.button.edit"
#define EDIT @"edit"
#define ACCOUNTS_USERPROFILE_BUTTON_DELETEACCOUNT @"accounts.userprofile.button.deleteAccount"
#define DELETE_ACCOUNT @"DELETE ACCOUNT"
#define ACCOUNTS_OWNEDALMOND_LABEL_YOUOWNTHISALMOND @"accounts.ownedAlmond.label.YouOwnThisAlmond"
#define YOU_OWN_THIS_ALMOND @"You own this Almond"
#define ACCOUNTS_SHAREDALMOND_LABEL_SHAREDWITHYOUBY @"accounts.sharedAlmond.label.SharedWithYouBy"
#define SHARED_WITH_YOU_BY @"Shared with you by"
#define ACCOUNTS_OWNEDALMOND_LABEL_SHAREDWITHOTHERS @"accounts.ownedAlmond.label.SharedWithOthers"
#define DEVICE_NAME @"DEVICE NAME"
#define ACCOUNTS_SHAREDALMOND_LABEL_DEVICENAME @"accounts.sharedAlmond.label.deviceName"
#define ACCOUNTS_OWNEDALMOND_BUTTON_UNLINK @"accounts.ownedAlmond.button.Unlink"
#define UNLINK @"Unlink"
#define ACCOUNTS_SHAREDALMOND_BUTTON_REMOVE @"accounts.sharedAlmond.button.Remove"
#define REMOVE @"Remove"
#define ACCOUNTS_OWNEDALMOND_TEXTFIELD_PLACEHOLDER @"accounts.ownedAlmond.textfield.placeholder.almondName"
#define ALMOND_NAME @"Almond Name"
#define ACCOUNTS_SHAREDALMOND_TEXTFIELD_PLACEHOLDER_ALMONDNAME @"accounts.sharedAlmond.textfield.placeholder.almondName"
#define ACCOUNTS_OWNEDALMOND_BUTTON_RENAMEDALMOND @"accounts.ownedAlmond.button.RenameAlmond"
#define RENAME_ALMOND @"Rename Almond"
#define ACCOUNTS_SHAREDALMOND_BUTTON_RENAMEALMOND @"accounts.sharedAlmond.button.RenameAlmond"
#define ACCOUNTS_OWNEDALMOND_LABEL_ACCESSEMAIL @"accounts.ownedAlmond.label.accessEmail"
#define ACCESS_EMAIL @"Access Email"
#define ACCOUNTS_OWNEDALMOND_BUTTON_REMOVE @"accounts.ownedAlmond.button.Remove"
#define ACCOUNTS_OWNED_BUTTON_INVITEMORE @"accounts.ownedAlmond.button.InviteMore"
#define INVITE_MORE @"Invite More"
#define DONE @"Done"
#define ACCOUNTS_USERPROFILE_BUTTON_EDIT @"accounts.userprofile.button.edit"
#define ACCOUNTS_USERPROFILE_BUTTON_DONE @"accounts.userprofile.button.done"
#define ACCOUNTS_ALERT_ONDELETEACCOUNT_TITLE @"accounts.alert.onDeleteAccount.title"
#define ACCOUNTS_ALERT_ONDELETEACCOUNT_MESSAGE @"accounts.alert.onDeleteAccount.message"
#define DELETING_THE_ACCOUNT_WILL_UNLINK_YOUR_ALMONDS_AND_DELETE_USER_PREFERENCES_TO_CONFIRM_ACCOUNT_DELETION_ENTER_YOUR_PASSWORD_BELOW @"Deleting the account will unlink your Almond(s) and delete user preferences. To confirm account deletion enter your password below."
#define ACCOUNTS_ALERT_ONDELETEACCOUNT_CANCEL @"accounts.alert.onDeleteAccount.Cancel"
#define CANCEL @"Cancel"
#define ACCOUNTS_ALERT_ONDELETE_DELETE @"accounts.alert.onDeleteAccount.delete"
#define ACCOUNTS_ITOAST_ALMONDNAMEMAX32CHARACTERS @"accounts.itoast.almondNameMax32Characters"
#define ACCOUNTS_SHAREDALMOND_BUTTON_RENAMEALMOND @"accounts.sharedAlmond.button.RenameAlmond"
#define ACCOUNTS_ITOAST_ALMONDNAMEMAX32CHARACTERS @"accounts.itoast.almondNameMax32Characters"
#define ALMOND_NAME_CANNOT_BE_MORE_THAN_32_CHARACTERS @"Almond Name cannot be more than 32 characters."
#define ACCOUNTS_HUD_CHANGEALMOND @"accounts.hud.changeAlmondName"
#define CHANGE_ALMOND_NAME @"Change almond name..."
#define ACCOUNTS_ALERT_ONUNLINKALMOND_TITLE @"accounts.alert.onUnlinkAlmond.title"
#define ACCOUNTS_UNLINKALMOND_FAILURE_DEFAULT @"accounts.unlinkAlmond.failure.default"
#define UNLINK_ALMOND_DEFAULT_RESPONSE  @"UnlinkAlmond_defaultresponse"
#define DELETE_ME_SECONDARY_USER_DEFAULT_RESPONSE @"DeleteMeSecondaryUser_defaultresponse"
#define USER_INVITE_DEFAULT_RESPONSE @"UserInvite_defaultresponse"
#define DELETE_SECONDARY_USER_DEFAULT_RESPONSE @"DeleteSecondaryUser_defaultresponse"
#define ME_AS_SECONDARY_USER_RESPONSE @"MeAsSecondaryUserResponse"
#define ALMOND_AFFILIATION_DATA_RESPONSE @"AlmondAffiliationDataResponse"
#define COMMAND_TYPE @"CommandType"
#define AFFILIATION_DATA @"AffiliationData"
#define GET_ALMOND_LIST @"GetAlmondList"
#define ALMOND_LIST_RESPONSE @"AlmondListResponse"
#define ALMOND_AFFILIATION_DATA @"AlmondAffiliationData"
#define USER_PROFILE_RESPONSE @"UserpProfileResponse"
#define SUCCESS @"Success"
#define FirstName @"FirstName"
#define LastName @"LastName"
#define Address1 @"Address1"
#define Address2 @"Address2"
#define Address3 @"Address3"
#define Country @"Country"
#define ZipCode @"ZipCode"
#define UPDATE_USERPROFILE_REQUEST @"UpdateUserProfileRequest"
#define ALMOND_NAME_CHANGE_RESPONSE @"AlmondNameChange_defaultresponse"
#define DELETE_SECONDARY_USER_REQUEST @"DeleteSecondaryUserRequest"
#define ALMOND_MAC @"almondMAC"
#define EMAIL_ID @"emailID"
#define DELETE_ME_AS_SECONDARY_USER_REQUEST @"DeleteMeSecondaryUserRequest"
#define Password @"password"
#define DELETE_ACCOUNT_REQUEST @"DeleteAccountRequest"
#define UNLINK_ALMOND_REQUEST @"UnlinkAlmondRequest"
#define USER_INVITE_REQUEST @"UserInviteRequest"
#define ME_AS_SECONDARY_USER_REQUEST @"MeAsSecondaryUserRequest"
